### ISSUE TITLE
Instructions Enhancement

### ISSUE THREAD

**Issue by thomasklau** [dculibrk/edge_boxes_with_python#1]
Hi,

Thanks so much for putting this script together. It's really helpful.

It almost works right out of the box. It would be good to explain explicitly that the user has to install pdollar's MATLAB toolbox in order to use this library. https://pdollar.github.io/toolbox/

Was scratching my head a bit until tried to run your wrapper in MATLAB and saw that functions were being called from the toolbox that wasn't installed.

Thomas

**Comment by Tom405** [comment]
Hi!
The x64 system doesn't need to install toolbox? Why the problem happened ,Undefined function 'getPrmDflt' for input arguments of type 'cell',  when I run the demo?
Thanks!

**Comment by Tom405** [comment]
Hi. I runned the python code, why the mat file is empty?

**Comment by dculibrk** [comment]
Hi,

I would need a bit more information on your concrete setup. Usually, an
empty mat file would suggest an error has occurred while running the
toolbox. And you need the toolbox, regardless of the system type.

Best,

d

Dr Dubravko Culibrk,
Research Fellow, Dept. of Information Engineering and Computer Science,
University of Trento, Italy
Associate Professor, Dept. of Industrial Engineering and
Management,University of Novi Sad, Serbia
Tel: +39 327 421-5568, +381(63) 10-28-269
www: www.dubravkoculibrk.org, www.qostream.org, www.panon.it

**Comment by codecolony** [comment]
One basic question, do we still need matlab installed to use this library?

**Comment by jimmy-dq** [comment]
Hi @thomasklau , I tried to run the python code, but failed:
Traceback (most recent call last):
  File "/home/wqq/External/Data/IDE/pycharm-community-2016.3.2/helpers/pydev/pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/wqq/External/Data/IDE/pycharm-community-2016.3.2/helpers/pydev/pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/wqq/DeepLearning/edge_boxes_with_python-master/edge_boxes.py", line 66, in <module>
    boxes = get_windows(image_filenames)
  File "/home/wqq/DeepLearning/edge_boxes_with_python-master/edge_boxes.py", line 36, in get_windows
    shlex.split(mc), stdout=open('/dev/null', 'w'), cwd=script_dirname)
  File "/home/wqq/anaconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/home/wqq/anaconda2/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

could you provide more information on your installation steps? Thank you very much.

**Comment by mangoHoli** [comment]
Hi, I install the toolbox and compile the mex file. But when i run the example by python edge_boxes.py
I got this error saying mat file empty.
edge_boxes_wrapper({'/home/hollyemotion/workspace/edge_boxes_with_python/000004.jpg','/home/hollyemotion/workspace/edge_boxes_with_python/001551.jpg'}, '/tmp/tmpyCbS4U.mat')
Traceback (most recent call last):
  File "edge_boxes.py", line 67, in <module>
    boxes = get_windows(image_filenames)
  File "edge_boxes.py", line 42, in get_windows
    all_boxes = list(scipy.io.loadmat(output_filename)['all_boxes'][0])
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 135, in loadmat
    MR = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 59, in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/miobase.py", line 224, in get_matfile_version
    raise MatReadError("Mat file appears to be empty")
scipy.io.matlab.miobase.MatReadError: Mat file appears to be empty

**Comment by fmsxwbh** [comment]
I had the same problem I am using Windows10 with MATLAB2016

**Comment by alexshaodong** [comment]
> Hi. I runned the python code, why the mat file is empty?

Hello. Can you teach me how to edge-boxes all pictures?

Do you handle it? And generate mat files containing boxes and boxscores. Thank you!

**Comment by alexshaodong** [comment]
> I had the same problem I am using Windows10 with MATLAB2016

Hello. Can you teach me how to edge-boxes all pictures?

Do you handle it? And generate mat files containing boxes and boxscores. Thank you!

**Comment by akhalayly** [comment]
Hello, We also had the same problem where the generated mat file is empty.
Would appreciate any help with solving this problem, been stuck with it a week now :(
Thanks in advance.

> Traceback (most recent call last):
  File "C:\Users\alikh\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-c224dada89f0>", line 1, in <module>
    runfile('C:/Users/alikh/Desktop/Project/test.py', wdir='C:/Users/alikh/Desktop/Project')
  File "C:\Program Files\JetBrains\PyCharm 2019.3.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.3.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/alikh/Desktop/Project/test.py", line 2, in <module>
    windows = edge_boxes.get_windows("C:\\Users\\alikh\\Desktop\\Project\\cow.jpg")
  File "C:\Users\alikh\Desktop\Project\edges\edge_boxes.py", line 42, in get_windows
    all_boxes = list(scipy.io.loadmat(output_filename)['all_boxes'][0])
  File "C:\Users\alikh\Anaconda3\lib\site-packages\scipy\io\matlab\mio.py", line 217, in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
  File "C:\Users\alikh\Anaconda3\lib\site-packages\scipy\io\matlab\mio.py", line 72, in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
  File "C:\Users\alikh\Anaconda3\lib\site-packages\scipy\io\matlab\miobase.py", line 224, in get_matfile_version
    raise MatReadError("Mat file appears to be empty")
**_scipy.io.matlab.miobase.MatReadError: Mat file appears to be empty_**
