### ISSUE TITLE
Empty mat files issue

### ISSUE THREAD

**Issue by akhalayly** [dculibrk/edge_boxes_with_python#3]
Hello, We also had the problem where the generated mat file is empty.
Would appreciate any help with solving this problem, been stuck with it a week now :(
Thanks in advance.

> Traceback (most recent call last):
File "C:\Users\alikh\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "", line 1, in
runfile('C:/Users/alikh/Desktop/Project/test.py', wdir='C:/Users/alikh/Desktop/Project')
File "C:\Program Files\JetBrains\PyCharm 2019.3.1\plugins\python\helpers\pydev_pydev_bundle\pydev_umd.py", line 197, in runfile
pydev_imports.execfile(filename, global_vars, local_vars) # execute the script
File "C:\Program Files\JetBrains\PyCharm 2019.3.1\plugins\python\helpers\pydev_pydev_imps_pydev_execfile.py", line 18, in execfile
exec(compile(contents+"\n", file, 'exec'), glob, loc)
File "C:/Users/alikh/Desktop/Project/test.py", line 2, in
windows = edge_boxes.get_windows("C:\Users\alikh\Desktop\Project\cow.jpg")
File "C:\Users\alikh\Desktop\Project\edges\edge_boxes.py", line 42, in get_windows
all_boxes = list(scipy.io.loadmat(output_filename)['all_boxes'][0])
File "C:\Users\alikh\Anaconda3\lib\site-packages\scipy\io\matlab\mio.py", line 217, in loadmat
MR, _ = mat_reader_factory(f, **kwargs)
File "C:\Users\alikh\Anaconda3\lib\site-packages\scipy\io\matlab\mio.py", line 72, in mat_reader_factory
mjv, mnv = get_matfile_version(byte_stream)
File "C:\Users\alikh\Anaconda3\lib\site-packages\scipy\io\matlab\miobase.py", line 224, in get_matfile_version
raise MatReadError("Mat file appears to be empty")
**_scipy.io.matlab.miobase.MatReadError: Mat file appears to be empty_**

**Comment by Haseeb-Muhammad** [comment]
Same error for me. Any fix found?
